/**
 * This browser's signing identity (docs/willow-ainmem-plan.md Task 5).
 *
 * One Ed25519 device key per ainmem user on this browser, generated by WebCrypto
 * as non-extractable and kept in IndexedDB — the private half never exists as
 * bytes. Its aindrive certificate and ainmem's binding (POST /api/willow/device)
 * are remembered in localStorage, so signing keeps working offline once they have
 * been fetched. A person with no aindrive account connected gets no signer: their
 * edits go unsigned, as before.
 */
import { generateDeviceKey, signEntry, signTransaction, toHex, utf8, type DeviceKey, type WireJson } from "@/lib/willow/entry";
import type { SignedEnvelope, Transaction } from "@/lib/transactions/types";

export interface Signer {
  key: DeviceKey;
  deviceKey: string;
  binding: string;
  /** the `_id/cert` entry for a drive, signed by this device (cached) */
  certEntry(driveId: string): Promise<WireJson>;
}

const DB = "ainmem-willow";
const STORE = "keys";

function openDb(): Promise<IDBDatabase> {
  return new Promise((res, rej) => {
    const r = indexedDB.open(DB, 1);
    r.onupgradeneeded = () => r.result.createObjectStore(STORE, { keyPath: "userId" });
    r.onsuccess = () => res(r.result);
    r.onerror = () => rej(r.error);
  });
}

async function keyFor(userId: string): Promise<DeviceKey> {
  const db = await openDb();
  const got = await new Promise<{ userId: string; privateKey: CryptoKey; publicKey: Uint8Array } | undefined>((res, rej) => {
    const r = db.transaction(STORE, "readonly").objectStore(STORE).get(userId);
    r.onsuccess = () => res(r.result);
    r.onerror = () => rej(r.error);
  });
  if (got) return { privateKey: got.privateKey, publicKey: got.publicKey };
  const fresh = await generateDeviceKey();
  await new Promise<void>((res, rej) => {
    const tx = db.transaction(STORE, "readwrite");
    tx.objectStore(STORE).put({ userId, privateKey: fresh.privateKey, publicKey: fresh.publicKey });
    tx.oncomplete = () => res();
    tx.onerror = () => rej(tx.error);
  });
  return fresh;
}

const memo = new Map<string, Promise<Signer | null>>();
const lsKey = (userId: string) => `ainmem-willow:${userId}`;

async function load(userId: string): Promise<Signer | null> {
  if (typeof indexedDB === "undefined" || !globalThis.crypto?.subtle) return null;
  let key: DeviceKey;
  try {
    key = await keyFor(userId);
  } catch {
    return null; // no IndexedDB or no Ed25519 in this browser: unsigned
  }
  const deviceKey = toHex(key.publicKey);
  let saved: { deviceKey: string; cert: unknown; binding: string } | null = null;
  try {
    saved = JSON.parse(localStorage.getItem(lsKey(userId)) ?? "null");
  } catch {}
  if (!saved || saved.deviceKey !== deviceKey) {
    const res = await fetch("/api/willow/device", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ deviceKey }),
    }).catch(() => null);
    if (!res?.ok) {
      memo.delete(userId); // offline or not connected yet: ask again next time
      return null;
    }
    const data = (await res.json()) as { cert: unknown; binding: string };
    saved = { deviceKey, cert: data.cert, binding: data.binding };
    try {
      localStorage.setItem(lsKey(userId), JSON.stringify(saved));
    } catch {}
  }
  const certJson = JSON.stringify(saved.cert);
  const certs = new Map<string, Promise<WireJson>>();
  return {
    key,
    deviceKey,
    binding: saved.binding,
    certEntry(driveId) {
      let p = certs.get(driveId);
      if (!p) certs.set(driveId, (p = signEntry(key, driveId, ["_id", "cert"], utf8(certJson))));
      return p;
    },
  };
}

/** The signer for this user on this browser, or null (unsigned). */
export function signerFor(userId: string): Promise<Signer | null> {
  let p = memo.get(userId);
  if (!p) memo.set(userId, (p = load(userId).catch(() => null)));
  return p;
}

/** Signs each transaction of a page in `teamspaceId`, linked to `driveId`, for the queue. */
export function transactionSigner(s: Signer, driveId: string, teamspaceId: string) {
  return async (t: Transaction): Promise<SignedEnvelope> => ({
    drive: driveId,
    entry: await signTransaction(s.key, { driveId, teamspaceId, t }),
    cert: await s.certEntry(driveId),
    binding: s.binding,
  });
}
