/** Categorized emoji dataset for the icon/emoji picker.
 *  Each entry: [emoji, searchTerms]. Search terms are lowercase, space-separated.
 *  Kept inline to avoid external dependencies (CSP blocks CDN fetches). */

export interface EmojiCategory {
  name: string;
  icon: string;
  emojis: [string, string][]; // [emoji, "search terms"]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: "Smileys",
    icon: "😀",
    emojis: [
      ["😀", "grinning face happy smile"],
      ["😃", "smiley face happy"],
      ["😄", "smile grin happy"],
      ["😁", "beaming grin teeth"],
      ["😆", "laughing squint"],
      ["😅", "sweat smile nervous"],
      ["🤣", "rofl rolling laughing"],
      ["😂", "joy tears laughing crying"],
      ["🙂", "slightly smiling"],
      ["😊", "blush happy warm"],
      ["😇", "angel innocent halo"],
      ["🥰", "love hearts face"],
      ["😍", "heart eyes love"],
      ["🤩", "star struck excited"],
      ["😘", "kiss blowing love"],
      ["😜", "wink tongue playful"],
      ["🤪", "zany crazy goofy"],
      ["😎", "cool sunglasses"],
      ["🤓", "nerd glasses smart"],
      ["🧐", "monocle thinking curious"],
      ["🤔", "thinking hmm pondering"],
      ["🤗", "hugging warm embrace"],
      ["🤫", "shushing quiet secret"],
      ["🫡", "salute respect"],
      ["😐", "neutral expressionless"],
      ["😑", "expressionless flat"],
      ["😶", "no mouth silent"],
      ["😏", "smirk sly"],
      ["😒", "unamused annoyed"],
      ["🙄", "eye roll annoyed"],
      ["😬", "grimace awkward"],
      ["😮‍💨", "exhale sigh relief"],
      ["😴", "sleeping zzz tired"],
      ["🤤", "drool yummy"],
      ["😷", "mask sick medical"],
      ["🤢", "nauseated sick green"],
      ["🤮", "vomit sick"],
      ["🤧", "sneezing tissue"],
      ["🥵", "hot sweating overheated"],
      ["🥶", "cold freezing frozen"],
      ["😵", "dizzy knocked out"],
      ["🤯", "mind blown exploding head"],
      ["😱", "scream fear shocked"],
      ["😨", "fearful scared"],
      ["😰", "anxious worried sweat"],
      ["😢", "crying sad tear"],
      ["😭", "sobbing crying loud"],
      ["😤", "angry huff steam"],
      ["😠", "angry mad"],
      ["😡", "rage furious red"],
      ["🤬", "cursing swearing angry"],
      ["👿", "imp evil angry"],
      ["💀", "skull dead death"],
      ["💩", "poop poo"],
      ["🤡", "clown face"],
      ["👻", "ghost boo halloween"],
      ["👽", "alien ufo space"],
      ["🤖", "robot bot machine"],
      ["🎃", "jack o lantern halloween pumpkin"],
    ],
  },
  {
    name: "People",
    icon: "👋",
    emojis: [
      ["👋", "wave hello hi greeting"],
      ["🤚", "raised hand stop"],
      ["✋", "hand stop high five"],
      ["🖐️", "hand fingers spread"],
      ["👌", "ok okay perfect"],
      ["🤌", "pinched fingers italian"],
      ["✌️", "peace victory two"],
      ["🤞", "crossed fingers luck hope"],
      ["🫰", "heart hands love"],
      ["🤙", "call me hand shaka"],
      ["👍", "thumbs up good approve like"],
      ["👎", "thumbs down bad disapprove dislike"],
      ["✊", "fist bump solidarity"],
      ["👊", "fist punch bump"],
      ["🤝", "handshake deal agreement"],
      ["👏", "clap applause praise"],
      ["🙌", "raised hands celebration hooray"],
      ["💪", "biceps strong muscle flex"],
      ["🖕", "middle finger"],
      ["👈", "point left back"],
      ["👉", "point right forward"],
      ["👆", "point up above"],
      ["👇", "point down below"],
      ["☝️", "index up one"],
      ["🙏", "pray please thank you hope folded hands"],
      ["💅", "nail polish"],
      ["👀", "eyes looking watching"],
      ["👁️", "eye see watch"],
      ["👤", "person silhouette user"],
      ["👥", "people group team"],
      ["🧑‍💻", "technologist developer programmer coder"],
      ["🧑‍🎨", "artist creative painter"],
      ["🧑‍🏫", "teacher professor educator"],
      ["🧑‍🔬", "scientist researcher lab"],
      ["🧑‍🚀", "astronaut space explorer"],
      ["🧑‍⚕️", "doctor health medical"],
    ],
  },
  {
    name: "Nature",
    icon: "🌿",
    emojis: [
      ["🐶", "dog puppy pet woof"],
      ["🐱", "cat kitty meow pet"],
      ["🐭", "mouse rat"],
      ["🐰", "rabbit bunny"],
      ["🦊", "fox clever"],
      ["🐻", "bear grizzly"],
      ["🐼", "panda bear"],
      ["🐨", "koala australia"],
      ["🦁", "lion king"],
      ["🐮", "cow moo"],
      ["🐷", "pig oink"],
      ["🐸", "frog toad ribbit"],
      ["🐵", "monkey face"],
      ["🐔", "chicken hen"],
      ["🐧", "penguin arctic"],
      ["🐦", "bird tweet"],
      ["🦅", "eagle bird prey"],
      ["🦋", "butterfly insect pretty"],
      ["🐛", "bug caterpillar insect"],
      ["🐝", "bee honeybee buzz"],
      ["🐞", "ladybug beetle"],
      ["🐙", "octopus tentacle"],
      ["🦈", "shark fish"],
      ["🐬", "dolphin flipper"],
      ["🐋", "whale ocean"],
      ["🐍", "snake serpent"],
      ["🦖", "dinosaur trex"],
      ["🦕", "sauropod dino brontosaurus"],
      ["🌸", "cherry blossom flower sakura"],
      ["🌹", "rose flower red love"],
      ["🌻", "sunflower yellow"],
      ["🌺", "hibiscus flower tropical"],
      ["🌿", "herb leaf green plant"],
      ["🍀", "four leaf clover luck"],
      ["🌱", "seedling sprout growing plant"],
      ["🌲", "evergreen tree pine"],
      ["🌳", "deciduous tree"],
      ["🌴", "palm tree tropical"],
      ["🍄", "mushroom fungus"],
      ["🌈", "rainbow colors arc"],
      ["⭐", "star yellow bright"],
      ["🌟", "glowing star sparkle"],
      ["✨", "sparkles magic glitter"],
      ["☀️", "sun sunny bright"],
      ["🌙", "crescent moon night"],
      ["🌍", "earth globe world africa europe"],
      ["🌊", "wave ocean water"],
      ["💧", "droplet water tear"],
      ["🔥", "fire flame hot lit"],
      ["❄️", "snowflake cold winter frozen"],
      ["💨", "wind dash fast breeze"],
      ["⚡", "lightning bolt zap electric thunder"],
    ],
  },
  {
    name: "Food",
    icon: "🍕",
    emojis: [
      ["🍎", "apple red fruit"],
      ["🍐", "pear fruit green"],
      ["🍊", "orange tangerine citrus"],
      ["🍋", "lemon yellow citrus"],
      ["🍌", "banana fruit yellow"],
      ["🍉", "watermelon melon fruit"],
      ["🍇", "grapes purple fruit"],
      ["🍓", "strawberry fruit berry red"],
      ["🫐", "blueberries berry"],
      ["🍑", "peach fruit"],
      ["🥑", "avocado guac green"],
      ["🥕", "carrot vegetable orange"],
      ["🌽", "corn maize vegetable"],
      ["🍔", "hamburger burger beef"],
      ["🍕", "pizza slice cheese"],
      ["🌮", "taco mexican"],
      ["🌯", "burrito wrap"],
      ["🍜", "noodles ramen bowl"],
      ["🍣", "sushi japanese fish"],
      ["🍱", "bento box lunch japanese"],
      ["🍩", "donut doughnut sweet"],
      ["🍪", "cookie sweet biscuit"],
      ["🎂", "birthday cake celebration"],
      ["🍰", "cake shortcake dessert"],
      ["🧁", "cupcake muffin sweet"],
      ["🍫", "chocolate candy bar"],
      ["🍿", "popcorn movie snack"],
      ["☕", "coffee hot cup beverage tea"],
      ["🍵", "tea cup green"],
      ["🧃", "juice box drink"],
      ["🍺", "beer mug drink ale"],
      ["🍷", "wine glass red drink"],
      ["🥂", "champagne cheers toast celebrate"],
    ],
  },
  {
    name: "Activities",
    icon: "⚽",
    emojis: [
      ["⚽", "soccer football ball sport"],
      ["🏀", "basketball ball sport"],
      ["🏈", "american football ball sport"],
      ["⚾", "baseball ball sport"],
      ["🎾", "tennis ball sport"],
      ["🏐", "volleyball ball sport"],
      ["🎮", "video game controller gaming"],
      ["🕹️", "joystick arcade gaming"],
      ["🎲", "dice game roll random"],
      ["🧩", "puzzle piece jigsaw"],
      ["♟️", "chess pawn strategy"],
      ["🎯", "target bullseye dart goal direct hit"],
      ["🎳", "bowling ball pins"],
      ["🎸", "guitar music rock instrument"],
      ["🎹", "piano keyboard music instrument"],
      ["🎺", "trumpet brass music"],
      ["🥁", "drum music beat percussion"],
      ["🎭", "performing arts theater drama mask"],
      ["🎨", "art palette paint creative"],
      ["🎬", "clapper movie film action"],
      ["🎤", "microphone singing karaoke"],
      ["🎧", "headphones music audio"],
      ["🏆", "trophy award winner cup champion"],
      ["🥇", "gold medal first winner"],
      ["🥈", "silver medal second"],
      ["🥉", "bronze medal third"],
      ["🏅", "medal sports achievement"],
      ["🎖️", "military medal honor"],
    ],
  },
  {
    name: "Travel",
    icon: "✈️",
    emojis: [
      ["🚗", "car automobile vehicle drive"],
      ["🚕", "taxi cab yellow"],
      ["🚌", "bus transit public"],
      ["🚎", "trolleybus transit"],
      ["🚀", "rocket launch space"],
      ["✈️", "airplane plane flight travel"],
      ["🚁", "helicopter chopper"],
      ["🛸", "flying saucer ufo alien"],
      ["⛵", "sailboat sailing"],
      ["🚢", "ship cruise boat"],
      ["🏠", "house home building"],
      ["🏢", "office building corporate"],
      ["🏫", "school education building"],
      ["🏥", "hospital medical building"],
      ["🏰", "castle palace kingdom european"],
      ["⛪", "church worship"],
      ["🗼", "tokyo tower"],
      ["🗽", "statue liberty new york"],
      ["🗻", "mount fuji mountain japan"],
      ["⛰️", "mountain peak"],
      ["🏖️", "beach umbrella vacation"],
      ["🏕️", "camping tent outdoor"],
      ["🌅", "sunrise morning dawn"],
      ["🌄", "sunrise mountain dawn"],
      ["🌃", "night cityscape stars"],
      ["🎡", "ferris wheel carnival amusement"],
      ["🎢", "roller coaster thrill ride"],
      ["🗺️", "world map atlas"],
      ["🧭", "compass navigation direction"],
    ],
  },
  {
    name: "Objects",
    icon: "💻",
    emojis: [
      ["📱", "phone mobile smartphone device"],
      ["💻", "laptop computer pc device"],
      ["🖥️", "desktop computer monitor screen"],
      ["⌨️", "keyboard typing input"],
      ["🖱️", "mouse computer click"],
      ["🖨️", "printer paper output"],
      ["📷", "camera photo picture"],
      ["📹", "video camera recording"],
      ["📺", "television tv screen"],
      ["🔋", "battery power charge"],
      ["🔌", "plug electric power"],
      ["💡", "light bulb idea bright"],
      ["🔦", "flashlight torch"],
      ["📦", "package box delivery"],
      ["📫", "mailbox letter mail"],
      ["✉️", "envelope email letter mail"],
      ["📝", "memo note write pencil"],
      ["📄", "document page file paper"],
      ["📁", "folder directory file"],
      ["🗂️", "card index dividers organize tabs"],
      ["📚", "books reading library stack"],
      ["📖", "open book reading"],
      ["📌", "pushpin pin location"],
      ["📎", "paperclip attach"],
      ["✂️", "scissors cut"],
      ["🔑", "key lock access"],
      ["🔒", "locked secure private"],
      ["🔓", "unlocked open"],
      ["🛡️", "shield protect security"],
      ["🔧", "wrench tool fix"],
      ["🔨", "hammer tool build"],
      ["⚙️", "gear settings config cog"],
      ["🧲", "magnet attract"],
      ["💎", "gem diamond jewel precious"],
      ["🏷️", "label tag price"],
      ["🧾", "receipt bill"],
      ["📊", "bar chart graph statistics data"],
      ["📈", "chart increasing growth trend up"],
      ["📉", "chart decreasing decline trend down"],
      ["📅", "calendar date schedule"],
      ["📆", "tear off calendar date"],
      ["🗓️", "spiral calendar planner"],
      ["⏰", "alarm clock time wake"],
      ["⏱️", "stopwatch timer"],
      ["⏳", "hourglass time running sand"],
      ["🔔", "bell notification alert"],
      ["🔕", "bell slash mute silent"],
      ["🎵", "music note song"],
      ["🎶", "music notes melody song"],
    ],
  },
  {
    name: "Symbols",
    icon: "💯",
    emojis: [
      ["❤️", "red heart love"],
      ["🧡", "orange heart"],
      ["💛", "yellow heart"],
      ["💚", "green heart"],
      ["💙", "blue heart"],
      ["💜", "purple heart"],
      ["🖤", "black heart"],
      ["🤍", "white heart"],
      ["💯", "hundred perfect score"],
      ["💢", "anger symbol"],
      ["💥", "collision explosion boom bang"],
      ["💫", "dizzy star"],
      ["💬", "speech bubble comment talk"],
      ["💭", "thought bubble think"],
      ["🗣️", "speaking head announce"],
      ["❗", "exclamation important alert"],
      ["❓", "question mark help"],
      ["‼️", "double exclamation important"],
      ["⚠️", "warning caution alert"],
      ["🚫", "prohibited forbidden no"],
      ["🔴", "red circle dot"],
      ["🟠", "orange circle dot"],
      ["🟡", "yellow circle dot"],
      ["🟢", "green circle dot"],
      ["🔵", "blue circle dot"],
      ["🟣", "purple circle dot"],
      ["⚪", "white circle dot"],
      ["⚫", "black circle dot"],
      ["✅", "check mark done yes complete"],
      ["❌", "cross mark no wrong cancel"],
      ["➕", "plus add new"],
      ["➖", "minus subtract remove"],
      ["➡️", "right arrow forward next"],
      ["⬅️", "left arrow back previous"],
      ["⬆️", "up arrow"],
      ["⬇️", "down arrow"],
      ["🔗", "link chain url"],
      ["📍", "pin location map"],
      ["🏁", "checkered flag finish race"],
      ["🚩", "red flag alert"],
      ["🔖", "bookmark mark save"],
      ["♻️", "recycle green environment"],
      ["🔄", "refresh reload sync"],
      ["ℹ️", "information info"],
    ],
  },
  {
    name: "Flags",
    icon: "🏳️",
    emojis: [
      ["🏳️", "white flag surrender"],
      ["🏴", "black flag"],
      ["🏳️‍🌈", "rainbow flag pride lgbtq"],
      ["🇺🇸", "usa united states america flag"],
      ["🇬🇧", "uk united kingdom britain flag"],
      ["🇫🇷", "france french flag"],
      ["🇩🇪", "germany german flag"],
      ["🇯🇵", "japan japanese flag"],
      ["🇰🇷", "korea korean south flag"],
      ["🇨🇳", "china chinese flag"],
      ["🇧🇷", "brazil brazilian flag"],
      ["🇮🇳", "india indian flag"],
      ["🇦🇺", "australia australian flag"],
      ["🇨🇦", "canada canadian flag"],
      ["🇪🇸", "spain spanish flag"],
      ["🇮🇹", "italy italian flag"],
      ["🇲🇽", "mexico mexican flag"],
    ],
  },
];

/** Flat list of all emojis for quick random pick. */
export const ALL_EMOJIS: string[] = EMOJI_CATEGORIES.flatMap((c) =>
  c.emojis.map(([e]) => e)
);
